config/routes.rb
def install_old_routes
  ActionController::Routing::Routes.draw do |map|
    # URL for items of type httpServer/XXX.git. Some versions of rails has problems with multiple regex expressions, so avoid...
    # Note that 'http_server_subdir' is either empty (default case) or ends in '/'.
    map.connect ":repo_path/*path", :prefix => (GitHostingConf.http_server_subdir rescue ""), :repo_path => /([^\/]+\/)*?[^\/]+\.git/, :controller => 'git_http'

    # Handle the public keys plugin to my/account.
    map.resources :public_keys, :controller => 'gitolite_public_keys', :path_prefix => 'my'
    map.connect 'my/account/public_key/:public_key_id', :controller => 'my', :action => 'account'
    map.connect 'users/:id/edit/public_key/:public_key_id', :controller => 'users', :action => 'edit', :conditions => {:method => [:get]}

    # Handle hooks and mirrors
    map.connect 'githooks', :controller => 'gitolite_hooks', :action => 'stub'
    map.connect 'githooks/post-receive', :controller => 'gitolite_hooks', :action => 'post_receive'
    map.connect 'githooks/test', :controller => 'gitolite_hooks', :action => 'test'

    map.with_options :controller => 'repositories' do |repo_mapper|
      repo_mapper.with_options :controller => 'repository_mirrors' do |mirror_views|
        mirror_views.connect 'repositories/:repository_id/mirrors/new', :action => 'create', :conditions => {:method => [:get, :post]}
        mirror_views.connect 'repositories/:repository_id/mirrors/edit/:id', :action => 'edit'
        mirror_views.connect 'repositories/:repository_id/mirrors/push/:id', :action => 'push'
        mirror_views.connect 'repositories/:repository_id/mirrors/update/:id', :action => 'update', :conditions => {:method => :post}
        mirror_views.connect 'repositories/:repository_id/mirrors/delete/:id', :action => 'destroy', :conditions => {:method => [:get, :delete]}
      end

      repo_mapper.with_options :controller => 'repository_post_receive_urls' do |post_receive_views|
        post_receive_views.connect 'repositories/:repository_id/post-receive-urls/new', :action => 'create', :conditions => {:method => [:get, :post]}
        post_receive_views.connect 'repositories/:repository_id/post-receive-urls/edit/:id', :action => 'edit'
        post_receive_views.connect 'repositories/:repository_id/post-receive-urls/update/:id', :action => 'update', :conditions => {:method => :post}
        post_receive_views.connect 'repositories/:repository_id/post-receive-urls/delete/:id', :action => 'destroy', :conditions => {:method => [:get, :delete]}
      end

      repo_mapper.with_options :controller => 'deployment_credentials' do |deploy_views|
        deploy_views.connect 'repositories/:repository_id/deployment-credentials/new', :action => 'create_with_key', :conditions => {:method => [:get, :post]}
        deploy_views.connect 'repositories/:repository_id/deployment-credentials/edit/:id', :action => 'edit'
        deploy_views.connect 'repositories/:repository_id/deployment-credentials/update/:id', :action => 'update', :conditions => {:method => :post}
        deploy_views.connect 'repositories/:repository_id/deployment-credentials/delete/:id', :action => 'destroy', :conditions => {:method => [:get, :delete]}
      end
    end
  end
end

def install_new_routes
  RedmineApp::Application.routes.draw do
    match ':repo_path/*path', :prefix => (GitHostingConf.http_server_subdir rescue ""), :repo_path => /([^\/]+\/)*?[^\/]+\.git/, :to => 'git_http#index'

    # Handle the public keys plugin to my/account.
    scope "/my" do
      resources :public_keys, :controller => 'gitolite_public_keys'
    end

    match 'my/account/public_key/:public_key_id', :to => 'my#account'
    match 'users/:id/edit/public_key/:public_key_id', :to => 'users#edit', :via => [:get]

    # Handle hooks and mirrors
    match 'githooks', :to => 'gitolite_hooks#stub'
    match 'githooks/test', :to => 'gitolite_hooks#test'
    match 'githooks/post-receive', :to => 'gitolite_hooks#post_receive'

    match 'repositories/:repository_id/mirrors/new',        :to => 'repository_mirrors#create', :via => [:get, :post]
    match 'repositories/:repository_id/mirrors/edit/:id',   :to => 'repository_mirrors#edit'
    match 'repositories/:repository_id/mirrors/push/:id',   :to => 'repository_mirrors#push'
    match 'repositories/:repository_id/mirrors/update/:id', :to => 'repository_mirrors#update', :via => [:post]
    match 'repositories/:repository_id/mirrors/delete/:id', :to => 'repository_mirrors#destroy', :via => [:get, :delete]

    match 'repositories/:repository_id/post-receive-urls/new',        :to => 'repository_post_receive_urls#create', :via => [:get, :post]
    match 'repositories/:repository_id/post-receive-urls/edit/:id',   :to => 'repository_post_receive_urls#edit'
    match 'repositories/:repository_id/post-receive-urls/update/:id', :to => 'repository_post_receive_urls#update', :via => [:post]
    match 'repositories/:repository_id/post-receive-urls/delete/:id', :to => 'repository_post_receive_urls#destroy', :via => [:get, :delete]

    match 'repositories/:repository_id/deployment-credentials/new',        :to => 'deployment_credentials#create_with_key', :via => [:get, :post]
    match 'repositories/:repository_id/deployment-credentials/edit/:id',   :to => 'deployment_credentials#edit'
    match 'repositories/:repository_id/deployment-credentials/update/:id', :to => 'deployment_credentials#update', :via => [:post]
    match 'repositories/:repository_id/deployment-credentials/delete/:id', :to => 'deployment_credentials#destroy', :via => [:get, :delete]
  end
end

if Rails::VERSION::MAJOR >= 3
  install_new_routes
else
  install_old_routes
end

app/views/repositories/_form.html.erb
<%= error_messages_for 'repository' %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag('application', :plugin => 'redmine_git_hosting') %>
  <%= stylesheet_link_tag('modalbox/modalbox', :plugin => 'redmine_git_hosting') %>
  <%= javascript_include_tag('modalbox/modalbox', :plugin => 'redmine_git_hosting') %>
<% end %>

<div class="box tabular">
  <% if @repository && @repository.is_a?(Repository::Git) && (GitHostingHelper.can_view_deployment_keys(@repository.project) || GitHostingHelper.can_view_post_receive_urls(@repository.project) || GitHostingHelper.can_view_mirrors(@repository.project)) %>
    <h3>Repository Options</h3>
  <% end %>

  <p>
    <%= label_tag('repository_scm', l(:label_scm)) %><%= scm_select_tag(@repository) %>
    <% if @repository && ! @repository.class.scm_available %>
      <em class="info error"><%= l(:text_scm_command_not_available) %></em>
    <% end %>
  </p>

  <p><%= f.check_box :is_default, :label => :field_repository_is_default %></p>
  <% if @repository && @repository.is_a?(Repository::Git) %>
    <p><%= f.text_field :identifier, :label => (@repository.new_record? ? :field_identifier : :label_identifier_cannot_be_changed), :disabled => !@repository.new_record? %></p>
  <% else %>
    <p><%= f.text_field :identifier %></p>
  <% end %>

  <% button_disabled = true %>
  <% if @repository %>
    <% button_disabled = ! @repository.class.scm_available %>
  <% end %>

  <% if @repository && @repository.is_a?(Repository::Git) %>
    <p>
      <%= label_tag  "extra[git_daemon]", l(:field_git_daemon) %>
      <%= select_tag "extra[git_daemon]", options_for_select([ [l(:label_disabled), "0"], [l(:label_enabled), "1"]], :selected=>(@project.is_public ? @repository.extra[:git_daemon].to_s : "0")), :disabled => !@project.is_public %>
    </p>

    <p>
      <%= label_tag  "extra[git_http]", l(:field_git_http) %>
      <%= select_tag "extra[git_http]", options_for_select([ [l(:label_disabled), "0"], [l(:label_https_only), "1"], [l(:label_https_and_http), "2"] ], :selected=>@repository.extra[:git_http].to_s) %>
    </p>

    <p>
      <%= label_tag  "extra[notify_cia]", l(:field_notify_cia) %>
      <%= select_tag "extra[notify_cia]", options_for_select([ [l(:label_disabled), "0"], [l(:label_enabled), "1"]], :selected=>@repository.extra[:notify_cia].to_s) %>
      <% if @repository.extra[:notify_cia].to_s == "1" %>
        <a id="notify_cia_test" href="<%= url_for(:controller => "gitolite_hooks", :action => "test", :projectid => @repository.project.identifier) %>"><%= l(:field_notify_cia_test) %></a>
        <em><b><span id="notify_cia_result"></span></b></em>
      <% end %>
    </p>

    <%= javascript_include_tag('notify_cia_test', :plugin => 'redmine_git_hosting') %>

    <br/>

  <% else %>
    <%= repository_field_tags(f, @repository) if @repository %>
  <% end %>

  <%= submit_tag(@repository.new_record? ? l(:button_create) : l(:button_save), :disabled => button_disabled) %>
  <%= link_to l(:button_cancel), settings_project_path(@project, :tab => 'repositories') %>
</div>

app/views/repositories/_git_urls.erb
<% if repository && repository.is_a?(Repository::Git) && Setting.plugin_redmine_git_hosting['gitRepositoriesShowUrl'].to_s != "false" %>
  <% content_for :header_tags do %>

    <%= stylesheet_link_tag('git_url_display', :plugin => 'redmine_git_hosting') %>
    <%= javascript_include_tag('git_url_display', :plugin => 'redmine_git_hosting') %>

    <%= stylesheet_link_tag('zero_clipboard', :plugin => 'redmine_git_hosting') %>
    <%= javascript_include_tag('ZeroClipboard', :plugin => 'redmine_git_hosting') %>
    <%= javascript_include_tag('zero_clipboard_setup', :plugin => 'redmine_git_hosting') %>

    <script type="text/javascript">
      guProjectName= "<%= GitHosting.git_access_url(repository)+'.git' %>";
      guSshURL = "<%= GitHosting.git_access_url(repository)+'.git' %>";
      guHttpURL = "<%= GitHosting.http_access_url(repository)+'.git' %>";
      guProjectIsPublic= <%= project.is_public.to_s %> ;
      guUser= "<%= User.current.login %>";
      guUserIsCommitter= <%= User.current.allowed_to?(:commit_access, project) ? "true" : "false" %> ;
      guGitUser="<%= Setting.plugin_redmine_git_hosting['gitUser'] %>";
      guGitServer="<%= Setting.plugin_redmine_git_hosting['gitServer'] %>";
      guHttpBase="<%= GitHosting.my_root_url %>"
      guHttpProto="<%=  repository.extra[:git_http].to_s == "2" ? "http" : "https" %>";

      if (!(window.Event === undefined) && !(Event.observe === undefined)) {
        Event.observe(window,"load", setGitUrlOnload);
      } else {
        window.onload = setGitUrlOnload;
      }

      ZeroClipboard.setMoviePath('<%= GitHostingHelper.plugin_asset_link('ZeroClipboard.swf') %>');
      setZeroClipboardInputSource("git_url_text");
    </script>
  <% end %>

  <% if (!User.current.anonymous?) || repository.extra[:git_http].to_s != "0" || (project.is_public && repository.extra[:git_daemon].to_s != "0" ) %>
    <div class="box">
      <div id="git_url_box">
        <h3>Repository Access Links:</h3>
        <div id="clipboard_container" title="<%= l(:label_copy_to_clipboard) %>" style="display: none;">
          <div id="clipboard_button"><%= image_tag 'paste.png', :plugin => 'redmine_git_hosting' %></div>
        </div>
        <ul id="git_url_list" >
          <% if !User.current.anonymous? %>
            <li><a id="git_url_ssh"  href="javascript:void(0)">SSH</a></li>
          <% end %>
          <% if repository.extra[:git_http].to_s != "0" %>
            <li><a id="git_url_http" href="javascript:void(0)">HTTP</a></li>
          <% end %>
          <% if project.is_public && repository.extra[:git_daemon].to_s != "0" %>
            <li><a id="git_url_git"  href="javascript:void(0)">Git</a></li>
          <% end %>
        </ul>
        <input id="git_url_text" name="git_url_text" readonly="readonly" value="" />
        <span id="git_url_desc">This URL has <span id="git_url_access">Read-Only</span> access.</span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/repositories/edit.html.erb
<h2><%= l(:label_repository) %></h2>

<% form = labelled_form_for :repository, @repository, :url => repository_path(@repository), :html => {:method => :put} do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>
<%= form if Rails::VERSION::MAJOR >= 3 %>

<% if @repository && @repository.is_a?(Repository::Git) && !(@repository.nil? || @repository.new_record?) %>
  <% if GitHostingHelper.can_view_deployment_keys(@repository.project) %>
    <%= render :partial => 'deployment_credentials/view_list' %>
  <% end %>

  <% if GitHostingHelper.can_view_post_receive_urls(@repository.project) %>
    <%= render :partial => 'repository_post_receive_urls/view_list' %>
  <% end %>

  <% if GitHostingHelper.can_view_mirrors(@repository.project) %>
    <%= render :partial => 'repository_mirrors/view_list' %>
  <% end %>
<% end %>

app/views/repositories/git_instructions.html.erb
<%# This is used to display basic git setup instructions, like on github... %>
<% flash.now[:warning] = "Repository is empty. Get started by following the instructions below." %>

<%= render :partial => 'git_urls', :locals => {:repository => @repository, :project => @project} %>

<% gitSHP = GitHostingConf.git_server.match(/:\d+$/) %>
<% git_ssh_url = "#{gitSHP ? 'ssh://' : ''}#{GitHostingConf.git_user}@#{GitHostingConf.git_server}#{gitSHP ? '/' : ':'}#{GitHosting.repository_name(@repository)}.git" %>

<div class="box">

  <br />

  <h2>Git Setup:</h2>
  <pre>
    <a href="http://git-scm.com/download" target="_blank">Download and Install Git</a>
    git config --global user.name "<%= User.current.name(:firstname_lastname) %>"
    git config --global user.email <%= User.current.mail %>
    <% if User.current.gitolite_public_keys.active.length == 0 %>
    <%= link_to "Upload SSH Public Key", {:controller => 'my', :action => 'account'} %>
  </pre>
    <% else %>
  </pre>
    <% end %>

  <h2>Repository Setup:</h2>
  <pre>
    mkdir <%= @repository.git_name %>
    cd <%= @repository.git_name %>
    git init
    touch readme.txt
    git add readme.txt
    git commit -m 'Initializing <%= @repository.git_label %> repository'
    git remote add origin <%= git_ssh_url %>
    git push -u origin master
  </pre>

  <h2>Existing Git Repo?</h2>
  <pre>
    cd existing_git_repo
    git remote add origin <%= git_ssh_url %>
    git push -u origin master
  </pre>

</div>

<% if @repositories.size > 1 %>
  <% content_for :sidebar do %>
    <h3><%= l(:label_repository_plural) %></h3>
    <p>
      <%= @repositories.sort.collect {|repo|
          link_to h(repo.name),
                  {:controller => 'repositories', :action => 'show',
                   :id => @project, :repository_id => repo.identifier_param, :rev => nil, :path => nil},
                   :class => 'repository' + (repo == @repository ? ' selected' : '')
          }.join('<br />').html_safe %>
    </p>
  <% end %>
<% end %>