config/routes.rb
def install_old_routes
  ActionController::Routing::Routes.draw do |map|
    # URL for items of type httpServer/XXX.git. Some versions of rails has problems with multiple regex expressions, so avoid...
    # Note that 'http_server_subdir' is either empty (default case) or ends in '/'.
    map.connect ":repo_path/*path", :prefix => (GitHostingConf.http_server_subdir rescue ""), :repo_path => /([^\/]+\/)*?[^\/]+\.git/, :controller => 'git_http'

    # Handle the public keys plugin to my/account.
    map.resources :public_keys, :controller => 'gitolite_public_keys', :path_prefix => 'my'
    map.connect 'my/account/public_key/:public_key_id', :controller => 'my', :action => 'account'
    map.connect 'users/:id/edit/public_key/:public_key_id', :controller => 'users', :action => 'edit', :conditions => {:method => [:get]}

    # Handle hooks and mirrors
    map.connect 'githooks', :controller => 'gitolite_hooks', :action => 'stub'
    map.connect 'githooks/post-receive', :controller => 'gitolite_hooks', :action => 'post_receive'
    map.connect 'githooks/test', :controller => 'gitolite_hooks', :action => 'test'

    map.with_options :controller => 'repositories' do |repo_mapper|
      repo_mapper.with_options :controller => 'repository_mirrors' do |mirror_views|
        mirror_views.connect 'repositories/:repository_id/mirrors/new', :action => 'create', :conditions => {:method => [:get, :post]}
        mirror_views.connect 'repositories/:repository_id/mirrors/edit/:id', :action => 'edit'
        mirror_views.connect 'repositories/:repository_id/mirrors/push/:id', :action => 'push'
        mirror_views.connect 'repositories/:repository_id/mirrors/update/:id', :action => 'update', :conditions => {:method => :post}
        mirror_views.connect 'repositories/:repository_id/mirrors/delete/:id', :action => 'destroy', :conditions => {:method => [:get, :delete]}
      end

      repo_mapper.with_options :controller => 'repository_post_receive_urls' do |post_receive_views|
        post_receive_views.connect 'repositories/:repository_id/post-receive-urls/new', :action => 'create', :conditions => {:method => [:get, :post]}
        post_receive_views.connect 'repositories/:repository_id/post-receive-urls/edit/:id', :action => 'edit'
        post_receive_views.connect 'repositories/:repository_id/post-receive-urls/update/:id', :action => 'update', :conditions => {:method => :post}
        post_receive_views.connect 'repositories/:repository_id/post-receive-urls/delete/:id', :action => 'destroy', :conditions => {:method => [:get, :delete]}
      end

      repo_mapper.with_options :controller => 'deployment_credentials' do |deploy_views|
        deploy_views.connect 'repositories/:repository_id/deployment-credentials/new', :action => 'create_with_key', :conditions => {:method => [:get, :post]}
        deploy_views.connect 'repositories/:repository_id/deployment-credentials/edit/:id', :action => 'edit'
        deploy_views.connect 'repositories/:repository_id/deployment-credentials/update/:id', :action => 'update', :conditions => {:method => :post}
        deploy_views.connect 'repositories/:repository_id/deployment-credentials/delete/:id', :action => 'destroy', :conditions => {:method => [:get, :delete]}
      end
    end
  end
end

def install_new_routes
  RedmineApp::Application.routes.draw do
    match ':repo_path/*path', :prefix => (GitHostingConf.http_server_subdir rescue ""), :repo_path => /([^\/]+\/)*?[^\/]+\.git/, :to => 'git_http#index'

    # Handle the public keys plugin to my/account.
    scope "/my" do
      resources :public_keys, :controller => 'gitolite_public_keys'
    end

    match 'my/account/public_key/:public_key_id', :to => 'my#account'
    match 'users/:id/edit/public_key/:public_key_id', :to => 'users#edit', :via => [:get]

    # Handle hooks and mirrors
    match 'githooks', :to => 'gitolite_hooks#stub'
    match 'githooks/test', :to => 'gitolite_hooks#test'
    match 'githooks/post-receive', :to => 'gitolite_hooks#post_receive'

    match 'repositories/:repository_id/mirrors/new',        :to => 'repository_mirrors#create', :via => [:get, :post]
    match 'repositories/:repository_id/mirrors/edit/:id',   :to => 'repository_mirrors#edit'
    match 'repositories/:repository_id/mirrors/push/:id',   :to => 'repository_mirrors#push'
    match 'repositories/:repository_id/mirrors/update/:id', :to => 'repository_mirrors#update', :via => [:post]
    match 'repositories/:repository_id/mirrors/delete/:id', :to => 'repository_mirrors#destroy', :via => [:get, :delete]

    match 'repositories/:repository_id/post-receive-urls/new',        :to => 'repository_post_receive_urls#create', :via => [:get, :post]
    match 'repositories/:repository_id/post-receive-urls/edit/:id',   :to => 'repository_post_receive_urls#edit'
    match 'repositories/:repository_id/post-receive-urls/update/:id', :to => 'repository_post_receive_urls#update', :via => [:post]
    match 'repositories/:repository_id/post-receive-urls/delete/:id', :to => 'repository_post_receive_urls#destroy', :via => [:get, :delete]

    match 'repositories/:repository_id/deployment-credentials/new',        :to => 'deployment_credentials#create_with_key', :via => [:get, :post]
    match 'repositories/:repository_id/deployment-credentials/edit/:id',   :to => 'deployment_credentials#edit'
    match 'repositories/:repository_id/deployment-credentials/update/:id', :to => 'deployment_credentials#update', :via => [:post]
    match 'repositories/:repository_id/deployment-credentials/delete/:id', :to => 'deployment_credentials#destroy', :via => [:get, :delete]
  end
end

if Rails::VERSION::MAJOR >= 3
  install_new_routes
else
  install_old_routes
end

app/controllers/gitolite_public_keys_controller.rb
class GitolitePublicKeysController < ApplicationController
  unloadable

  before_filter :require_login
  before_filter :set_user_variable
  before_filter :set_users_keys, :except => [:index, :new, :reset_rss_key]
  before_filter :find_gitolite_public_key, :except => [:index, :new, :reset_rss_key, :create]

  helper :issues
  helper :users
  helper :custom_fields

  helper :gitolite_public_keys
  include GitolitePublicKeysHelper

  def edit
    redirect_to url_for(:controller=>'my', :action=>'account', :public_key_id => @gitolite_public_key[:id])
  end

  def destroy
    GitHostingObserver.set_update_active(false)
    if !request.get?
      destroy_key
    end
    redirect_to @redirect_url
    GitHostingObserver.set_update_active(true)
  end

  def update
    GitHostingObserver.set_update_active(false)
    if !request.get?
      if params[:save_button]
        if @gitolite_public_key.update_attributes(params[:gitolite_public_key])
          flash[:notice] = l(:notice_public_key_updated, :title=>keylabel(@gitolite_public_key))

          respond_to do |format|
            format.html { redirect_to @redirect_url }
            format.js
          end
        else
          respond_to do |format|
            format.html {
              flash[:error] = l(:error_public_key_create_failed)
              # This doesn't give back validation errors (messy!)
              redirect_to @redirect_url
            }
            format.js {
              render :action => "form_error"
            }
          end
        end
      else
        destroy_key if params[:delete_button]

        respond_to do |format|
          format.html { redirect_to @redirect_url }
          format.js
        end
      end
    end
    GitHostingObserver.set_update_active(true)
  end

  def create
    GitHostingObserver.set_update_active(false)
    @gitolite_public_key = GitolitePublicKey.new(params[:gitolite_public_key].merge(:user => @user))
    if params[:create_button]
      if @gitolite_public_key.save
        flash[:notice] = l(:notice_public_key_added, :title=>keylabel(@gitolite_public_key))

        respond_to do |format|
          format.html { redirect_to @redirect_url }
          format.js
        end
      else
        respond_to do |format|
          format.html {
            flash[:error] = l(:error_public_key_create_failed)
            # This doesn't give back validation errors (messy!)
            redirect_to @redirect_url
          }
          format.js {
            render :action => "form_error"
          }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @redirect_url }
        format.js { render :update }
      end
    end
    GitHostingObserver.set_update_active(true)
  end

  protected

  def set_user_variable
    if params[:user_id]
      @user = (params[:user_id]=='current') ? User.current : User.find_by_id(params[:user_id])
      if @user
        @redirect_url = url_for(:controller => 'users', :action => 'edit', :id => params[:user_id], :tab => 'keys')
      else
        render_404
      end
    else
      @user = User.current
      @redirect_url = url_for(:controller => 'my', :action => 'account')
    end
  end

  def set_users_keys
    @gitolite_user_keys = @user.gitolite_public_keys.active.user_key.find(:all,:order => 'title ASC, created_at ASC')
    @gitolite_deploy_keys = @user.gitolite_public_keys.active.deploy_key.find(:all,:order => 'title ASC, created_at ASC')
    @gitolite_public_keys = @gitolite_user_keys + @gitolite_deploy_keys
  end

  def find_gitolite_public_key
    key = GitolitePublicKey.find_by_id(params[:id])
    if key and (@user == key.user || @user.admin?)
      @gitolite_public_key = key
    elsif key
      render_403
    else
      render_404
    end
  end

  def destroy_key
    @gitolite_public_key[:active] = 0

    # Since we are ultimately destroying this key, just force save (since old keys may fail new validations)
    @gitolite_public_key.save((Rails::VERSION::STRING.split('.')[0].to_i > 2) ? { :validate => false } : false)

    flash[:notice] = l(:notice_public_key_deleted, :title=>keylabel(@gitolite_public_key))
  end

end

app/helpers/gitolite_public_keys_helper.rb
module GitolitePublicKeysHelper

  def gitolite_public_keys_status_options_for_select(user, selected)
    key_count_by_active = user.gitolite_public_keys.count(:group => 'active').to_hash
    options_for_select([[l(:label_all), nil],
          ["#{l(:status_active)} (#{key_count_by_active[true].to_i})", GitolitePublicKey::STATUS_ACTIVE],
          ["#{l(:status_locked)} (#{key_count_by_active[false].to_i})", GitolitePublicKey::STATUS_LOCKED]], selected)
  end

  def keylabel(key)
    if key.user == User.current
      "\"#{key.title}\""
    else
      "\"#{key.user.login}@#{key.title}\""
    end
  end

  def keylabel_text(key)
    if key.user == User.current
      "#{key.title}"
    else
      "#{key.user.login}@#{key.title}"
    end
  end

  def wrap_and_join(in_array,my_or="or")
    my_array = in_array.map{|x| "\"#{x}\""}
    length = my_array.length
    return my_array if length < 2
    my_array[length-1] = my_or+" "+my_array[length-1]
    if length == 2
      my_array.join(' ')
    else
      my_array.join(', ')
    end
  end

end

app/views/gitolite_public_keys/_view.html.erb
<%= stylesheet_link_tag('application', :plugin => 'redmine_git_hosting')%>

<fieldset class="box">
  <legend><%=l(:label_public_keys)%></legend>

  <% if !@gitolite_user_keys.empty? || @gitolite_deploy_keys.empty? %>
    <fieldset class="public_key_view">
      <legend><%= @gitolite_deploy_keys.empty? ? l(:label_current_public_keys) : l(:label_current_user_keys) %></legend>
      <table class="list">
        <% if @gitolite_user_keys.empty? %>
          <tr><td><label><%=l(:label_no_public_keys)%></label></td></tr>
        <%end %>
        <% @gitolite_user_keys.each do |key| %>
          <tr class="<%= curcycle=cycle('odd', 'even'); (@gitolite_public_key == key) ? 'highlight' : curcycle %>">
            <td style="text-align:left;"><%= h(key) %></td>
            <% if params[:id] %>
              <td style="width:60%; text-align:center"><%= "keydir/#{key.identifier}.pub" %></td>
            <% end %>
            <td style="width:10%;" class="buttons">
              <%= link_to(l(:button_edit), { :public_key_id => key.id, :tab => params[:id]&&'keys'}, :class => 'icon icon-edit') %>
              <%= link_to(l(:button_delete), public_key_path(key, :user_id=>params[:id]), :method => 'delete', :class => 'icon icon-del', :confirm=>l(:text_gitolite_key_destroy_confirmation, :title=>keylabel(key))) %>
            </td>
          </tr>
        <% end %>
      </table>
    </fieldset><br/>
  <% end %>

  <% if !@gitolite_deploy_keys.empty? %>
    <fieldset class="public_key_view">
      <legend><%= l(:label_current_deploy_keys)%></legend>
      <table class="list">
        <% if @gitolite_deploy_keys.empty? %>
          <tr><td><label><%=l(:label_no_public_keys)%></label></td></tr>
        <%end %>
        <% @gitolite_deploy_keys.each do |key| %>
          <tr class="<%= curcycle=cycle('odd', 'even'); (@gitolite_public_key == key) ? 'highlight' : curcycle %>">
            <td style="text-align:left;"><%= h(key) %></td>
            <% if params[:id] %>
              <td style="width:60%; text-align:center"><%= "keydir/#{key.identifier}.pub" %></td>
            <% end %>
            <td style="width:10%;" class="buttons">
              <%= link_to(l(:button_edit), { :public_key_id => key.id, :tab => params[:id]&&'keys'}, :class => 'icon icon-edit') %>
              <%= link_to(l(:button_delete), public_key_path(key, :user_id=>params[:id]), :method => 'delete', :class => 'icon icon-del', :confirm=>l(:text_gitolite_key_destroy_confirmation, :title=>keylabel(key))) %>
            </td>
          </tr>
        <% end %>
      </table>
    </fieldset><br/>
  <% end %>

  <% @new_key = @gitolite_public_key.new_record? %>

  <fieldset class="public_key_view">
    <legend><%= @new_key ? l(:label_public_key_new) : l(:label_public_key_edit) %></legend>
    <div id="validation_messages"><%= error_messages_for 'gitolite_public_key' %></div>
    <% form = labelled_form_for @gitolite_public_key,
        :as => :gitolite_public_key,
        :url=>{:controller=>'gitolite_public_keys', :action=>@new_key ? 'create' : 'update', :id=>@gitolite_public_key.id, :user_id=>params[:id], :tab => params[:id]&&'keys'},
        :html => {:method=>(@new_key ? :post : :put)} do |f| %>

      <p><%= f.text_field :title, :label => :label_identifier_can_be_arbitrary, :required => true, :style => 'width:99%;' %></p>

      <% if @gitolite_public_key.key_type==1 || GitHostingHelper.can_create_deployment_keys_for_some_project(@user) %>
        <div class="tabular">
          <p>
            <%= f.select :key_type, options_for_select([[l(:label_user_key),0],[l(:label_deploy_key),1]], :selected => @gitolite_public_key.key_type, :disabled => (@new_key ? [] : [0,1])), :required => true, :label => :field_key_type %>
          </p>
          <div id="key_type_options" style="display:none">
            <p>
              <%= f.check_box :delete_when_unused, :required => true, :label => :field_delete_when_unused %>
            </p>
          </div>
        </div>
      <% end %>

      <p><%= f.text_area :key, :label => (@new_key? :label_cut_and_paste : :field_public_key), :required => true, :disabled => !@new_key,
              :style => "width:99%;height:200px;overflow:auto;",
              :cols => nil, :rows => nil %>

      <%= hidden_field_tag :button_submit_field, "true" %>

      <% if !@new_key%>
        <em><%= l(:label_key_cannot_be_changed_please_create_new_key) %></em>
        </p>
        <%= submit_tag l(:button_save), :name=>'save_button' %>
        <%= submit_tag l(:button_delete), :name=>'delete_button', :confirm => l(:text_gitolite_key_destroy_confirmation,:title=>(@gitolite_public_key[:title].blank? ? l(:text_this_key) : keylabel(@gitolite_public_key))) %>
        <%= submit_tag l(:button_cancel), :name=>'cancel_button' %>
      <% else %>
        </p>
        <%= submit_tag l(:button_create), :name=>'create_button' %>
        <% mystyle = (@gitolite_public_key.errors.any? ? '' : 'style="display:none;"') %>
        <span id="cancel_button_div" <%= mystyle %> >
          <%= submit_tag l(:button_cancel), :name=>'cancel_button' %>
        </span>
      <% end %>
    <% end %>
    <%= form if Rails::VERSION::MAJOR >= 3 %>
  </fieldset>
</fieldset>

<script type="text/javascript">
  function load_form_actions() {
    key_type_change($('#public_key_key_type')[0]);
    $('#public_key_key_type').bind('change', function() { key_type_change(this) });
    $('input[type="submit"]').each(function() {
      if (this.name.indexOf("__") != 0) {
        myname = this.name;
        this.name = "__"+this.name;
        set_submit_change(this,myname);
      }
    });
  }

  function key_type_change(elem) {
    if (!elem.length) return;
    var idx = elem.selectedIndex;
    if (idx == 0) {
      $('#key_type_options').hide();
      $('#public_key_delete_when_unused').prop("checked", true);
    } else {
      $('#key_type_options').show();
    }
    if (typeof(Modalbox) != 'undefined' ) { Modalbox.resizeToContent(); }
  }

  function set_submit_change(item,myname) {
    $(item).bind('click', function() {
      $('#button_submit_field').prop("name", myname);
    });
  }

  $(window).load(load_form_actions);
</script>

app/views/gitolite_public_keys/create.js.erb
window.location.href = "<%= @redirect_url %>";

app/views/gitolite_public_keys/form_error.js.erb
$('#validation_messages').replaceWith("<%= escape_javascript(error_messages_for 'gitolite_public_key') %>");
$('div.notice').each( function() { $(this).hide(); });
$('#cancel_button_div').show();

app/views/gitolite_public_keys/update.js.erb
window.location.href = "<%= @redirect_url %>";